/*
 * This file is generated by jOOQ.
*/
package net.cloudopt.next.example.orm;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import net.cloudopt.next.example.orm.tables.Todo;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CloudoptExample extends SchemaImpl {

    private static final long serialVersionUID = 1604250783;

    /**
     * The reference instance of <code>cloudopt_example</code>
     */
    public static final CloudoptExample CLOUDOPT_EXAMPLE = new CloudoptExample();

    /**
     * The table <code>cloudopt_example.todo</code>.
     */
    public final Todo TODO = net.cloudopt.next.example.orm.tables.Todo.TODO;

    /**
     * No further instances allowed
     */
    private CloudoptExample() {
        super("cloudopt_example", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Todo.TODO);
    }
}
