/*
 * This file is generated by jOOQ.
*/
package net.cloudopt.next.example.orm;


import javax.annotation.Generated;

import net.cloudopt.next.example.orm.tables.Todo;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>cloudopt_example</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index TODO_PRIMARY = Indexes0.TODO_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index TODO_PRIMARY = createIndex("PRIMARY", Todo.TODO, new OrderField[] { Todo.TODO.ID }, true);
    }
}
