/*
 * This file is generated by jOOQ.
*/
package net.cloudopt.next.example.orm;


import javax.annotation.Generated;

import net.cloudopt.next.example.orm.tables.Todo;
import net.cloudopt.next.example.orm.tables.records.TodoRecord;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>cloudopt_example</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<TodoRecord, Integer> IDENTITY_TODO = Identities0.IDENTITY_TODO;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TodoRecord> KEY_TODO_PRIMARY = UniqueKeys0.KEY_TODO_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<TodoRecord, Integer> IDENTITY_TODO = createIdentity(Todo.TODO, Todo.TODO.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<TodoRecord> KEY_TODO_PRIMARY = createUniqueKey(Todo.TODO, "KEY_todo_PRIMARY", Todo.TODO.ID);
    }
}
