/*
 * This file is generated by jOOQ.
*/
package net.cloudopt.next.example.orm;


import javax.annotation.Generated;

import net.cloudopt.next.example.orm.tables.Todo;


/**
 * Convenience access to all tables in cloudopt_example
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>cloudopt_example.todo</code>.
     */
    public static final Todo TODO = net.cloudopt.next.example.orm.tables.Todo.TODO;
}
