/*
 * This file is generated by jOOQ.
*/
package net.cloudopt.next.example.orm.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import net.cloudopt.next.example.orm.tables.Todo;
import net.cloudopt.next.example.orm.tables.records.TodoRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TodoDao extends DAOImpl<TodoRecord, net.cloudopt.next.example.orm.tables.pojos.Todo, Integer> {

    /**
     * Create a new TodoDao without any configuration
     */
    public TodoDao() {
        super(Todo.TODO, net.cloudopt.next.example.orm.tables.pojos.Todo.class);
    }

    /**
     * Create a new TodoDao with an attached configuration
     */
    public TodoDao(Configuration configuration) {
        super(Todo.TODO, net.cloudopt.next.example.orm.tables.pojos.Todo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(net.cloudopt.next.example.orm.tables.pojos.Todo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<net.cloudopt.next.example.orm.tables.pojos.Todo> fetchById(Integer... values) {
        return fetch(Todo.TODO.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public net.cloudopt.next.example.orm.tables.pojos.Todo fetchOneById(Integer value) {
        return fetchOne(Todo.TODO.ID, value);
    }

    /**
     * Fetch records that have <code>text IN (values)</code>
     */
    public List<net.cloudopt.next.example.orm.tables.pojos.Todo> fetchByText(String... values) {
        return fetch(Todo.TODO.TEXT, values);
    }

    /**
     * Fetch records that have <code>state IN (values)</code>
     */
    public List<net.cloudopt.next.example.orm.tables.pojos.Todo> fetchByState(Integer... values) {
        return fetch(Todo.TODO.STATE, values);
    }

    /**
     * Fetch records that have <code>time IN (values)</code>
     */
    public List<net.cloudopt.next.example.orm.tables.pojos.Todo> fetchByTime(Timestamp... values) {
        return fetch(Todo.TODO.TIME, values);
    }
}
