/*
 * This file is generated by jOOQ.
 */
package net.cloudopt.next.example.model;


import net.cloudopt.next.example.model.tables.Todo;


/**
 * Convenience access to all tables in blog
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>blog.todo</code>.
     */
    public static final Todo TODO = Todo.TODO;
}
